In [5]:
import pandas as pd

In [59]:
df = pd.read_csv('food.csv')

In [13]:
df.head(7)

       title       cuisine      type  state famous location   taste  price
0       dosa  south indian   healthy  solid         chennai   spicy     60
1      maggi       chinese  fastfood  solid          hostel   spicy     30
2       susi      japanese   healthy  solid           tokyo   spicy    200
3   dal bati    rajasthani   healthy  mixed    chokhi dhani   spicy    150
4  pav bhaji  north indian  fastfood  mixed           delhi   spicy     60
5      pizza       italian  fastfood  solid          domino  cheesy    300
6     burger       italian  fastfood  solid     burger king   spicy     80

# Pandas Functionalities

## 1. Basic Attributes

In [8]:
df.ndim

2

In [9]:
df.shape

(31, 7)

In [10]:
df.index

RangeIndex(start=0, stop=31, step=1)

In [11]:
df.columns

Index(['title', 'cuisine', 'type', 'state', 'famous location', 'taste',
       'price'],
      dtype='object')

In [12]:
df.loc[5]

title                 pizza
cuisine             italian
type               fastfood
state                 solid
famous location      domino
taste                cheesy
price                   300
Name: 5, dtype: object

In [14]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
title,dosa,maggi,susi,dal bati,pav bhaji,pizza,burger,noodles,litti chokha,curry,...,tea,pasta,chhole kulche,idli sambhar,coffee,lasgana,pastry,cakes,veg roll,kimchi
cuisine,south indian,chinese,japanese,rajasthani,north indian,italian,italian,chinese,bihari,indian,...,global,italian,delhi,south indian,global,italian,global,global,chinese,korean
type,healthy,fastfood,healthy,healthy,fastfood,fastfood,fastfood,fastfood,healthy,healthy,...,hot drink,fastfood,fastfood,healthy,drink,fastfood,desert,desert,fastfood,healthy
state,solid,solid,solid,mixed,mixed,solid,solid,solid,mixed,liquid,...,liquid,solid,mixed,mixed,liquid,mixed,solid,solid,solid,solid
famous location,chennai,hostel,tokyo,chokhi dhani,delhi,domino,burger king,china town,patna,amritsar,...,gulab,cluster,amul parlour,dosa seth,NBC,mamus in fusion,bakery,bakery,roll express,seol
taste,spicy,spicy,spicy,spicy,spicy,cheesy,spicy,spicy,spicy,spicy,...,sweet,spicy,spicy,spicy,sweet,neutral,sweet,sweet,spicy,spicy
price,60,30,200,150,60,300,80,60,120,110,...,5,150,70,50,50,250,30,450,50,350

In [16]:
df.T[4]

title                 pav bhaji
cuisine            north indian
type                   fastfood
state                     mixed
famous location           delhi
taste                     spicy
price                        60
Name: 4, dtype: object

In [17]:
df.values.tolist()

[['dosa', 'south indian', 'healthy', 'solid', 'chennai', 'spicy', 60],
 ['maggi', 'chinese', 'fastfood', 'solid', 'hostel', 'spicy', 30],
 ['susi', 'japanese', 'healthy', 'solid', 'tokyo', 'spicy', 200],
 ['dal bati', 'rajasthani', 'healthy', 'mixed', 'chokhi dhani', 'spicy', 150],
 ['pav bhaji', 'north indian', 'fastfood', 'mixed', 'delhi', 'spicy', 60],
 ['pizza', 'italian', 'fastfood', 'solid', 'domino', 'cheesy', 300],
 ['burger', 'italian', 'fastfood', 'solid', 'burger king', 'spicy', 80],
 ['noodles', 'chinese', 'fastfood', 'solid', 'china town', 'spicy', 60],
 ['litti chokha', 'bihari', 'healthy', 'mixed', 'patna', 'spicy', 120],
 ['curry', 'indian', 'healthy', 'liquid', 'amritsar', 'spicy', 110],
 ['chapati', 'indian', 'healthy', 'solid', 'sweet home', 'neutral', 15],
 ['momos', 'chinese', 'fastfood', 'solid', 'thapa ke momos', 'spicy', 80],
 ['sandwich', 'italian', 'fastfood', 'solid', 'kanha', 'spicy', 50],
 ['tacos', 'mexican', 'fastfood', 'solid', 'GT', 'spicy', 150],
 ['vada pav', 'mumbai', 'fastfood', 'solid', 'ghunghroo seth', 'spicy', 40],
 ['maza', 'USA', 'cold drink', 'liquid', 'bakery', 'sweet', 10],
 ['panipuri',
  'north indian',
  'fastfood',
  'mixed',
  'golu ke gol gappe',
  'spicy',
  10],
 ['coca cola', 'USA', 'cold drink', 'liquid', 'bakery', 'sweet', 20],
 ['curd', 'indian', 'healthy', 'liquid', 'dairy', 'sweet', 15],
 ['lassi', 'punjabi', 'cold drink', 'liquid', 'dairy', 'sweet', 15],
 ['chhole bhature', 'punjabi', 'fastfood', 'mixed', 'delhi', 'spicy', 50],
 ['tea', 'global', 'hot drink', 'liquid', 'gulab', 'sweet', 5],
 ['pasta', 'italian', 'fastfood', 'solid', 'cluster', 'spicy', 150],
 ['chhole kulche', 'delhi', 'fastfood', 'mixed', 'amul parlour', 'spicy', 70],
 ['idli sambhar',
  'south indian',
  'healthy',
  'mixed',
  'dosa seth',
  'spicy',
  50],
 ['coffee', 'global', 'drink', 'liquid', 'NBC', 'sweet', 50],
 ['lasgana',
  'italian',
  'fastfood',
  'mixed',
  'mamus in fusion',
  'neutral',
  250],
 ['pastry', 'global', 'desert', 'solid', 'bakery', 'sweet', 30],
 ['cakes', 'global', 'desert', 'solid', 'bakery', 'sweet', 450],
 ['veg roll', 'chinese', 'fastfood', 'solid', 'roll express', 'spicy', 50],
 ['kimchi', 'korean', 'healthy', 'solid', 'seol', 'spicy', 350]]

In [18]:
df.values.tolist()[5][4]

'domino'

In [20]:
df.sample(4)

,title,cuisine,type,state,famous location,taste,price
7,noodles,chinese,fastfood,solid,china town,spicy,60
16,panipuri,north indian,fastfood,mixed,golu ke gol gappe,spicy,10
23,chhole kulche,delhi,fastfood,mixed,amul parlour,spicy,70
29,veg roll,chinese,fastfood,solid,roll express,spicy,50

In [21]:
df['type'].unique()

array(['healthy', 'fastfood', 'cold drink', 'hot drink', 'drink',
       'desert'], dtype=object)

In [22]:
df['type'].nunique()

6

In [23]:
df['type'].value_counts()

type
fastfood      15
healthy        9
cold drink     3
desert         2
hot drink      1
drink          1
Name: count, dtype: int64

In [24]:
df.drop('cuisine',axis=1)

             title        type   state    famous location    taste  price
0             dosa     healthy   solid            chennai    spicy     60
1            maggi    fastfood   solid             hostel    spicy     30
2             susi     healthy   solid              tokyo    spicy    200
3         dal bati     healthy   mixed       chokhi dhani    spicy    150
4        pav bhaji    fastfood   mixed              delhi    spicy     60
5            pizza    fastfood   solid             domino   cheesy    300
6           burger    fastfood   solid        burger king    spicy     80
7          noodles    fastfood   solid         china town    spicy     60
8     litti chokha     healthy   mixed              patna    spicy    120
9            curry     healthy  liquid           amritsar    spicy    110
10         chapati     healthy   solid         sweet home  neutral     15
11           momos    fastfood   solid     thapa ke momos    spicy     80
12        sandwich    fastfood   solid              kanha    spicy     50
13           tacos    fastfood   solid                 GT    spicy    150
14        vada pav    fastfood   solid     ghunghroo seth    spicy     40
15            maza  cold drink  liquid             bakery    sweet     10
16        panipuri    fastfood   mixed  golu ke gol gappe    spicy     10
17       coca cola  cold drink  liquid             bakery    sweet     20
18            curd     healthy  liquid              dairy    sweet     15
19           lassi  cold drink  liquid              dairy    sweet     15
20  chhole bhature    fastfood   mixed              delhi    spicy     50
21             tea   hot drink  liquid              gulab    sweet      5
22           pasta    fastfood   solid            cluster    spicy    150
23   chhole kulche    fastfood   mixed       amul parlour    spicy     70
24    idli sambhar     healthy   mixed          dosa seth    spicy     50
25          coffee       drink  liquid                NBC    sweet     50
26         lasgana    fastfood   mixed    mamus in fusion  neutral    250
27          pastry      desert   solid             bakery    sweet     30
28           cakes      desert   solid             bakery    sweet    450
29        veg roll    fastfood   solid       roll express    spicy     50
30          kimchi     healthy   solid               seol    spicy    350

In [25]:
df.drop(['cuisine','state'],axis=1,inplace=True)

In [26]:
df

             title        type    famous location    taste  price
0             dosa     healthy            chennai    spicy     60
1            maggi    fastfood             hostel    spicy     30
2             susi     healthy              tokyo    spicy    200
3         dal bati     healthy       chokhi dhani    spicy    150
4        pav bhaji    fastfood              delhi    spicy     60
5            pizza    fastfood             domino   cheesy    300
6           burger    fastfood        burger king    spicy     80
7          noodles    fastfood         china town    spicy     60
8     litti chokha     healthy              patna    spicy    120
9            curry     healthy           amritsar    spicy    110
10         chapati     healthy         sweet home  neutral     15
11           momos    fastfood     thapa ke momos    spicy     80
12        sandwich    fastfood              kanha    spicy     50
13           tacos    fastfood                 GT    spicy    150
14        vada pav    fastfood     ghunghroo seth    spicy     40
15            maza  cold drink             bakery    sweet     10
16        panipuri    fastfood  golu ke gol gappe    spicy     10
17       coca cola  cold drink             bakery    sweet     20
18            curd     healthy              dairy    sweet     15
19           lassi  cold drink              dairy    sweet     15
20  chhole bhature    fastfood              delhi    spicy     50
21             tea   hot drink              gulab    sweet      5
22           pasta    fastfood            cluster    spicy    150
23   chhole kulche    fastfood       amul parlour    spicy     70
24    idli sambhar     healthy          dosa seth    spicy     50
25          coffee       drink                NBC    sweet     50
26         lasgana    fastfood    mamus in fusion  neutral    250
27          pastry      desert             bakery    sweet     30
28           cakes      desert             bakery    sweet    450
29        veg roll    fastfood       roll express    spicy     50
30          kimchi     healthy               seol    spicy    350

## 2. Descriptive/Statistical Function

In [29]:
df['state'].value_counts()

state
solid     16
mixed      8
liquid     7
Name: count, dtype: int64

In [30]:
df.sum()

title              dosamaggisusidal batipav bhajipizzaburgernoodl...
cuisine            south indianchinesejapaneserajasthaninorth ind...
type               healthyfastfoodhealthyhealthyfastfoodfastfoodf...
state              solidsolidsolidmixedmixedsolidsolidsolidmixedl...
famous location    chennaihosteltokyochokhi dhanidelhidominoburge...
taste              spicyspicyspicyspicyspicycheesyspicyspicyspicy...
price                                                           3080
dtype: object

In [31]:
df['price'].sum()

3080

In [37]:
df[df['cuisine']=='italian']['price'].sum()  # Total price for Italian cuisine

830

In [35]:
df[df['cuisine']=='italian']['price'].mean()  # Mean price for Italian cuisine

166.0

In [38]:
df[df['cuisine']=='italian']['price'].std()

107.37783756436893

In [39]:
df[df['cuisine']=='italian']['price'].var()

11530.0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            31 non-null     object
 1   cuisine          31 non-null     object
 2   type             31 non-null     object
 3   state            31 non-null     object
 4   famous location  31 non-null     object
 5   taste            31 non-null     object
 6   price            31 non-null     int64
dtypes: int64(1), object(6)
memory usage: 1.8+ KB

In [41]:
df.describe()

            price
count   31.000000
mean    99.354839
std    108.195363
min      5.000000
25%     30.000000
50%     60.000000
75%    135.000000
max    450.000000

In [42]:
df.describe(include='all')

       title  cuisine      type  state famous location  taste       price
count     31       31        31     31              31     31   31.000000
unique    31       15         6      3              26      4         NaN
top     dosa  italian  fastfood  solid          bakery  spicy         NaN
freq       1        5        15     16               4     20         NaN
mean     NaN      NaN       NaN    NaN             NaN    NaN   99.354839
std      NaN      NaN       NaN    NaN             NaN    NaN  108.195363
min      NaN      NaN       NaN    NaN             NaN    NaN    5.000000
25%      NaN      NaN       NaN    NaN             NaN    NaN   30.000000
50%      NaN      NaN       NaN    NaN             NaN    NaN   60.000000
75%      NaN      NaN       NaN    NaN             NaN    NaN  135.000000
max      NaN      NaN       NaN    NaN             NaN    NaN  450.000000

## 3. String Functions

In [43]:
df

,title,cuisine,type,state,famous location,taste,price
0,dosa,south indian,healthy,solid,chennai,spicy,60
1,maggi,chinese,fastfood,solid,hostel,spicy,30
2,susi,japanese,healthy,solid,tokyo,spicy,200
3,dal bati,rajasthani,healthy,mixed,chokhi dhani,spicy,150
4,pav bhaji,north indian,fastfood,mixed,delhi,spicy,60
5,pizza,italian,fastfood,solid,domino,cheesy,300
6,burger,italian,fastfood,solid,burger king,spicy,80
7,noodles,chinese,fastfood,solid,china town,spicy,60
8,litti chokha,bihari,healthy,mixed,patna,spicy,120
9,curry,indian,healthy,liquid,amritsar,spicy,110
10,chapati,indian,healthy,solid,sweet home,neutral,15
11,momos,chinese,fastfood,solid,thapa ke momos,spicy,80
12,sandwich,italian,fastfood,solid,kanha,spicy,50
13,tacos,mexican,fastfood,solid,GT,spicy,150
14,vada pav,mumbai,fastfood,solid,ghunghroo seth,spicy,40
15,maza,USA,cold drink,liquid,bakery,sweet,10
16,panipuri,north indian,fastfood,mixed,golu ke gol gappe,spicy,10
17,coca cola,USA,cold drink,liquid,bakery,sweet,20
18,curd,indian,healthy,liquid,dairy,sweet,15
19,lassi,punjabi,cold drink,liquid,dairy,sweet,15
20,chhole bhature,punjabi,fastfood,mixed,delhi,spicy,50
21,tea,global,hot drink,liquid,gulab,sweet,5
22,pasta,italian,fastfood,solid,cluster,spicy,150
23,chhole kulche,delhi,fastfood,mixed,amul parlour,spicy,70
24,idli sambhar,south indian,healthy,mixed,dosa seth,spicy,50
25,coffee,global,drink,liquid,NBC,sweet,50
26,lasgana,italian,fastfood,mixed,mamus in fusion,neutral,250
27,pastry,global,desert,solid,bakery,sweet,30
28,cakes,global,desert,solid,bakery,sweet,450
29,veg roll,chinese,fastfood,solid,roll express,spicy,50
30,kimchi,korean,healthy,solid,seol,spicy,350

In [44]:
cui = df['cuisine']

In [45]:
cui

0     south indian
1          chinese
2         japanese
3       rajasthani
4     north indian
5          italian
6          italian
7          chinese
8           bihari
9           indian
10          indian
11         chinese
12         italian
13         mexican
14          mumbai
15             USA
16    north indian
17             USA
18          indian
19         punjabi
20         punjabi
21          global
22         italian
23           delhi
24    south indian
25          global
26         italian
27          global
28          global
29         chinese
30          korean
Name: cuisine, dtype: object

In [46]:
cui.str.split()

0     [south, indian]
1           [chinese]
2          [japanese]
3        [rajasthani]
4     [north, indian]
5           [italian]
6           [italian]
7           [chinese]
8            [bihari]
9            [indian]
10           [indian]
11          [chinese]
12          [italian]
13          [mexican]
14           [mumbai]
15              [USA]
16    [north, indian]
17              [USA]
18           [indian]
19          [punjabi]
20          [punjabi]
21           [global]
22          [italian]
23            [delhi]
24    [south, indian]
25           [global]
26          [italian]
27           [global]
28           [global]
29          [chinese]
30           [korean]
Name: cuisine, dtype: object

In [47]:
df[cui.str.split().str.len()==2]        ## str accessor

,title,cuisine,type,state,famous location,taste,price
0,dosa,south indian,healthy,solid,chennai,spicy,60
4,pav bhaji,north indian,fastfood,mixed,delhi,spicy,60
16,panipuri,north indian,fastfood,mixed,golu ke gol gappe,spicy,10
24,idli sambhar,south indian,healthy,mixed,dosa seth,spicy,50

In [48]:
df['cuisine'] = cui.str.upper()
df

,title,cuisine,type,state,famous location,taste,price
0,dosa,SOUTH INDIAN,healthy,solid,chennai,spicy,60
1,maggi,CHINESE,fastfood,solid,hostel,spicy,30
2,susi,JAPANESE,healthy,solid,tokyo,spicy,200
3,dal bati,RAJASTHANI,healthy,mixed,chokhi dhani,spicy,150
4,pav bhaji,NORTH INDIAN,fastfood,mixed,delhi,spicy,60
5,pizza,ITALIAN,fastfood,solid,domino,cheesy,300
6,burger,ITALIAN,fastfood,solid,burger king,spicy,80
7,noodles,CHINESE,fastfood,solid,china town,spicy,60
8,litti chokha,BIHARI,healthy,mixed,patna,spicy,120
9,curry,INDIAN,healthy,liquid,amritsar,spicy,110
10,chapati,INDIAN,healthy,solid,sweet home,neutral,15
11,momos,CHINESE,fastfood,solid,thapa ke momos,spicy,80
12,sandwich,ITALIAN,fastfood,solid,kanha,spicy,50
13,tacos,MEXICAN,fastfood,solid,GT,spicy,150
14,vada pav,MUMBAI,fastfood,solid,ghunghroo seth,spicy,40
15,maza,USA,cold drink,liquid,bakery,sweet,10
16,panipuri,NORTH INDIAN,fastfood,mixed,golu ke gol gappe,spicy,10
17,coca cola,USA,cold drink,liquid,bakery,sweet,20
18,curd,INDIAN,healthy,liquid,dairy,sweet,15
19,lassi,PUNJABI,cold drink,liquid,dairy,sweet,15
20,chhole bhature,PUNJABI,fastfood,mixed,delhi,spicy,50
21,tea,GLOBAL,hot drink,liquid,gulab,sweet,5
22,pasta,ITALIAN,fastfood,solid,cluster,spicy,150
23,chhole kulche,DELHI,fastfood,mixed,amul parlour,spicy,70
24,idli sambhar,SOUTH INDIAN,healthy,mixed,dosa seth,spicy,50
25,coffee,GLOBAL,drink,liquid,NBC,sweet,50
26,lasgana,ITALIAN,fastfood,mixed,mamus in fusion,neutral,250
27,pastry,GLOBAL,desert,solid,bakery,sweet,30
28,cakes,GLOBAL,desert,solid,bakery,sweet,450
29,veg roll,CHINESE,fastfood,solid,roll express,spicy,50
30,kimchi,KOREAN,healthy,solid,seol,spicy,350

In [67]:
df['cuisine upper'] = cui.str.upper()
df

,title,cuisine,type,state,famous location,taste,price,cuisine upper
0,dosa,SOUTH INDIAN,healthy,solid,chennai,spicy,60,SOUTH INDIAN
1,maggi,CHINESE,fastfood,solid,hostel,spicy,30,CHINESE
2,susi,JAPANESE,healthy,solid,tokyo,spicy,200,JAPANESE
3,dal bati,RAJASTHANI,healthy,mixed,chokhi dhani,spicy,150,RAJASTHANI
4,pav bhaji,NORTH INDIAN,fastfood,mixed,delhi,spicy,60,NORTH INDIAN
5,pizza,ITALIAN,fastfood,solid,domino,cheesy,300,ITALIAN
6,burger,ITALIAN,fastfood,solid,burger king,spicy,80,ITALIAN
7,noodles,CHINESE,fastfood,solid,china town,spicy,60,CHINESE
8,litti chokha,BIHARI,healthy,mixed,patna,spicy,120,BIHARI
9,curry,INDIAN,healthy,liquid,amritsar,spicy,110,INDIAN
10,chapati,INDIAN,healthy,solid,sweet home,neutral,15,INDIAN
11,momos,CHINESE,fastfood,solid,thapa ke momos,spicy,80,CHINESE
12,sandwich,ITALIAN,fastfood,solid,kanha,spicy,50,ITALIAN
13,tacos,MEXICAN,fastfood,solid,GT,spicy,150,MEXICAN
14,vada pav,MUMBAI,fastfood,solid,ghunghroo seth,spicy,40,MUMBAI
15,maza,USA,cold drink,liquid,bakery,sweet,10,USA
16,panipuri,NORTH INDIAN,fastfood,mixed,golu ke gol gappe,spicy,10,NORTH INDIAN
17,coca cola,USA,cold drink,liquid,bakery,sweet,20,USA
18,curd,INDIAN,healthy,liquid,dairy,sweet,15,INDIAN
19,lassi,PUNJABI,cold drink,liquid,dairy,sweet,15,PUNJABI
20,chhole bhature,PUNJABI,fastfood,mixed,delhi,spicy,50,PUNJABI
21,tea,GLOBAL,hot drink,liquid,gulab,sweet,5,GLOBAL
22,pasta,ITALIAN,fastfood,solid,cluster,spicy,150,ITALIAN
23,chhole kulche,DELHI,fastfood,mixed,amul parlour,spicy,70,DELHI
24,idli sambhar,SOUTH INDIAN,healthy,mixed,dosa seth,spicy,50,SOUTH INDIAN
25,coffee,GLOBAL,drink,liquid,NBC,sweet,50,GLOBAL
26,lasgana,ITALIAN,fastfood,mixed,mamus in fusion,neutral,250,ITALIAN
27,pastry,GLOBAL,desert,solid,bakery,sweet,30,GLOBAL
28,cakes,GLOBAL,desert,solid,bakery,sweet,450,GLOBAL
29,veg roll,CHINESE,fastfood,solid,roll express,spicy,50,CHINESE
30,kimchi,KOREAN,healthy,solid,seol,spicy,350,KOREAN

## 4. Function Application and Iteration

In [49]:
df['cuisine'].apply(lambda x:len(x.split()))

0     2
1     1
2     1
3     1
4     2
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    2
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    2
25    1
26    1
27    1
28    1
29    1
30    1
Name: cuisine, dtype: int64

In [50]:
df

,title,cuisine,type,state,famous location,taste,price
0,dosa,SOUTH INDIAN,healthy,solid,chennai,spicy,60
1,maggi,CHINESE,fastfood,solid,hostel,spicy,30
2,susi,JAPANESE,healthy,solid,tokyo,spicy,200
3,dal bati,RAJASTHANI,healthy,mixed,chokhi dhani,spicy,150
4,pav bhaji,NORTH INDIAN,fastfood,mixed,delhi,spicy,60
5,pizza,ITALIAN,fastfood,solid,domino,cheesy,300
6,burger,ITALIAN,fastfood,solid,burger king,spicy,80
7,noodles,CHINESE,fastfood,solid,china town,spicy,60
8,litti chokha,BIHARI,healthy,mixed,patna,spicy,120
9,curry,INDIAN,healthy,liquid,amritsar,spicy,110
10,chapati,INDIAN,healthy,solid,sweet home,neutral,15
11,momos,CHINESE,fastfood,solid,thapa ke momos,spicy,80
12,sandwich,ITALIAN,fastfood,solid,kanha,spicy,50
13,tacos,MEXICAN,fastfood,solid,GT,spicy,150
14,vada pav,MUMBAI,fastfood,solid,ghunghroo seth,spicy,40
15,maza,USA,cold drink,liquid,bakery,sweet,10
16,panipuri,NORTH INDIAN,fastfood,mixed,golu ke gol gappe,spicy,10
17,coca cola,USA,cold drink,liquid,bakery,sweet,20
18,curd,INDIAN,healthy,liquid,dairy,sweet,15
19,lassi,PUNJABI,cold drink,liquid,dairy,sweet,15
20,chhole bhature,PUNJABI,fastfood,mixed,delhi,spicy,50
21,tea,GLOBAL,hot drink,liquid,gulab,sweet,5
22,pasta,ITALIAN,fastfood,solid,cluster,spicy,150
23,chhole kulche,DELHI,fastfood,mixed,amul parlour,spicy,70
24,idli sambhar,SOUTH INDIAN,healthy,mixed,dosa seth,spicy,50
25,coffee,GLOBAL,drink,liquid,NBC,sweet,50
26,lasgana,ITALIAN,fastfood,mixed,mamus in fusion,neutral,250
27,pastry,GLOBAL,desert,solid,bakery,sweet,30
28,cakes,GLOBAL,desert,solid,bakery,sweet,450
29,veg roll,CHINESE,fastfood,solid,roll express,spicy,50
30,kimchi,KOREAN,healthy,solid,seol,spicy,350

In [52]:
df[df['cuisine'].apply(lambda x:len(x.split()))==2]

,title,cuisine,type,state,famous location,taste,price
0,dosa,SOUTH INDIAN,healthy,solid,chennai,spicy,60
4,pav bhaji,NORTH INDIAN,fastfood,mixed,delhi,spicy,60
16,panipuri,NORTH INDIAN,fastfood,mixed,golu ke gol gappe,spicy,10
24,idli sambhar,SOUTH INDIAN,healthy,mixed,dosa seth,spicy,50

In [55]:
df[df['cuisine']=='GLOBAL']['type']=='desert'

21    False
25    False
27     True
28     True
Name: type, dtype: bool

In [57]:
df['price']=df[['cuisine','type','price']].apply(lambda x: 'free' if(x['cuisine']=='GLOBAL')and (x['type']=='desert') else x['price'] ,axis=1)
df

,title,cuisine,type,state,famous location,taste,price
0,dosa,SOUTH INDIAN,healthy,solid,chennai,spicy,60
1,maggi,CHINESE,fastfood,solid,hostel,spicy,30
2,susi,JAPANESE,healthy,solid,tokyo,spicy,200
3,dal bati,RAJASTHANI,healthy,mixed,chokhi dhani,spicy,150
4,pav bhaji,NORTH INDIAN,fastfood,mixed,delhi,spicy,60
5,pizza,ITALIAN,fastfood,solid,domino,cheesy,300
6,burger,ITALIAN,fastfood,solid,burger king,spicy,80
7,noodles,CHINESE,fastfood,solid,china town,spicy,60
8,litti chokha,BIHARI,healthy,mixed,patna,spicy,120
9,curry,INDIAN,healthy,liquid,amritsar,spicy,110
10,chapati,INDIAN,healthy,solid,sweet home,neutral,15
11,momos,CHINESE,fastfood,solid,thapa ke momos,spicy,80
12,sandwich,ITALIAN,fastfood,solid,kanha,spicy,50
13,tacos,MEXICAN,fastfood,solid,GT,spicy,150
14,vada pav,MUMBAI,fastfood,solid,ghunghroo seth,spicy,40
15,maza,USA,cold drink,liquid,bakery,sweet,10
16,panipuri,NORTH INDIAN,fastfood,mixed,golu ke gol gappe,spicy,10
17,coca cola,USA,cold drink,liquid,bakery,sweet,20
18,curd,INDIAN,healthy,liquid,dairy,sweet,15
19,lassi,PUNJABI,cold drink,liquid,dairy,sweet,15
20,chhole bhature,PUNJABI,fastfood,mixed,delhi,spicy,50
21,tea,GLOBAL,hot drink,liquid,gulab,sweet,5
22,pasta,ITALIAN,fastfood,solid,cluster,spicy,150
23,chhole kulche,DELHI,fastfood,mixed,amul parlour,spicy,70
24,idli sambhar,SOUTH INDIAN,healthy,mixed,dosa seth,spicy,50
25,coffee,GLOBAL,drink,liquid,NBC,sweet,50
26,lasgana,ITALIAN,fastfood,mixed,mamus in fusion,neutral,250
27,pastry,GLOBAL,desert,solid,bakery,sweet,free
28,cakes,GLOBAL,desert,solid,bakery,sweet,free
29,veg roll,CHINESE,fastfood,solid,roll express,spicy,50
30,kimchi,KOREAN,healthy,solid,seol,spicy,350

## Groupby

In [61]:
df[df['state']=='solid']['price'].mean()

130.9375

In [62]:
df[df['state']=='liquid']['price'].mean()

32.142857142857146

In [63]:
df[df['state']=='mixed']['price'].mean()

95.0

In [66]:
df.groupby('state')[['price']].mean()

             price
state
liquid   32.142857
mixed    95.000000
solid   130.937500

In [81]:
df.groupby('state')

In [82]:
df.groupby('state').describe()

       price
       count        mean         std   min   25%   50%    75%    max
state
liquid   7.0   32.142857   37.289089   5.0  12.5  15.0   35.0  110.0
mixed    8.0   95.000000   76.345081  10.0  50.0  65.0  127.5  250.0
solid   16.0  130.937500  130.207767  15.0  47.5  70.0  162.5  450.0

In [83]:
df.groupby('state').describe(include ='all').T

state        liquid     mixed  solid
title count       7         8     16
      unique      7         8     16
      top     curry  dal bati   dosa
      freq        1         1      1
      mean      NaN       NaN    NaN
...             ...       ...    ...
price min       5.0      10.0   15.0
      25%      12.5      50.0   47.5
      50%      15.0      65.0   70.0
      75%      35.0     127.5  162.5
      max     110.0     250.0  450.0

[66 rows x 3 columns]

In [84]:
df.groupby('state').describe(include = 'all').T
pd.set_option('display.max_rows',None)
df.groupby('state').describe(include = 'all').T

state                       liquid         mixed       solid
title           count            7             8          16
                unique           7             8          16
                top          curry      dal bati        dosa
                freq             1             1           1
                mean           NaN           NaN         NaN
                std            NaN           NaN         NaN
                min            NaN           NaN         NaN
                25%            NaN           NaN         NaN
                50%            NaN           NaN         NaN
                75%            NaN           NaN         NaN
                max            NaN           NaN         NaN
cuisine         count            7             8          16
                unique           4             7           9
                top         indian  north indian     chinese
                freq             2             2           4
                mean           NaN           NaN         NaN
                std            NaN           NaN         NaN
                min            NaN           NaN         NaN
                25%            NaN           NaN         NaN
                50%            NaN           NaN         NaN
                75%            NaN           NaN         NaN
                max            NaN           NaN         NaN
type            count            7             8          16
                unique           4             2           3
                top     cold drink      fastfood    fastfood
                freq             3             5          10
                mean           NaN           NaN         NaN
                std            NaN           NaN         NaN
                min            NaN           NaN         NaN
                25%            NaN           NaN         NaN
                50%            NaN           NaN         NaN
                75%            NaN           NaN         NaN
                max            NaN           NaN         NaN
famous location count            7             8          16
                unique           5             7          15
                top         bakery         delhi      bakery
                freq             2             2           2
                mean           NaN           NaN         NaN
                std            NaN           NaN         NaN
                min            NaN           NaN         NaN
                25%            NaN           NaN         NaN
                50%            NaN           NaN         NaN
                75%            NaN           NaN         NaN
                max            NaN           NaN         NaN
taste           count            7             8          16
                unique           2             2           4
                top          sweet         spicy       spicy
                freq             6             7          12
                mean           NaN           NaN         NaN
                std            NaN           NaN         NaN
                min            NaN           NaN         NaN
                25%            NaN           NaN         NaN
                50%            NaN           NaN         NaN
                75%            NaN           NaN         NaN
                max            NaN           NaN         NaN
price           count          7.0           8.0        16.0
                unique         NaN           NaN         NaN
                top            NaN           NaN         NaN
                freq           NaN           NaN         NaN
                mean     32.142857          95.0    130.9375
                std      37.289089     76.345081  130.207767
                min            5.0          10.0        15.0
                25%           12.5          50.0        47.5
                50%           15.0          65.0        70.0
                75%           35.0         127.5       162.5
                max          110.0         250.0       450.0